services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    # ports:
    #   - 4200:80

  gateway-srv:
    build:
      context: ./GatewayService
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user-srv:
    build:
      context: ./UserManagement
    environment:
      - DB_URL=jdbc:postgresql://user-srv-db:5432/joetrading
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - SERVER_PORT=80
    depends_on:
      - user-srv-db

  user-srv-db:
    image: postgres:16
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joetrading

  order-srv:
    build:
      context: ./OrderProcessingService
    environment:
      - DB_URL=jdbc:postgresql://order-srv-db:5432/joetrading
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=80
      - API_KEY=$API_KEY
    depends_on:
      - order-srv-db

  order-srv-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joetrading


volumes:
  rabbitmq_data:
