services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joetrading
    ports:
      - "5432:5432"

  nats:
    image: nats:2.6.0
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
