name: Build and Test User Management Service

on:
  pull_request:
    paths:
      - 'UserManagement/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk-jammy

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: usermanagement
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
            UserManagement/.gradle/caches
            UserManagement/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('UserManagement/**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run tests
      working-directory: UserManagement
      env:
        DB_URL: jdbc:postgresql://postgres:5432/usermanagement
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        JWT_SECRET: ${{ github.sha }}
      run: bash ./gradlew test

    - name: Build with Gradle
      working-directory: UserManagement
      run: bash ./gradlew build
