name: Build and Test User Management Service

on:
  pull_request:
    paths:
      - 'UserManagement/**'
  push:
    paths:
      - 'UserManagement/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
            UserManagement/.gradle/caches
            UserManagement/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('UserManagement/**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run tests
      working-directory: UserManagement
      run: bash ./gradlew test

    - name: Build with Gradle
      working-directory: UserManagement
      run: bash ./gradlew build
